### PR TITLE
peek, enhancement: fill fringes

### LINKED ISSUE #91: Enhancement request: stroking fringe area with citre-peek-border face
It will improve the visual feedback of citre-peek window.

### PR DESCRIPTION
**Pull request by masatake**
Close #91.

Signed-off-by: Masatake YAMATO <yamato@redhat.com>

### CODE REVIEW

**Comment by AmaiKinono** [comment]
Great idea!

**Comment by AmaiKinono** [comment]
I tested it a bit. It doesn't turn out to be very good-looking.

There are some weird white dashes (actually they are the `vertical-bar` bitmap):

image

The only solution I know is to define an empty bitmap by ourself:

```elisp
(define-fringe-bitmap 'citre-peek-fringe [0])
```

and the `display` property should be like

```elisp
'(left-fringe citre-peek-fringe citre-peek-border-face)
```

Then the dashes should gone.

Also, some definition info is lost.

**Comment by AmaiKinono** [comment]
`Symbol’s function definition is void: define-fringe-bitmap`

I saw this. We are having some hard times with Emacs 26 :(

Another annoying thing is `rx` on Emacs 26 doesn't support certain constructs.

**Comment by masatake** [comment]
> I saw this. We are having some hard times with Emacs 26 :(

Do you know any solution?

**Comment by masatake** [comment]
It seems that it is up to whether GUI is available or not.

**Comment by AmaiKinono** [comment]
> It seems that it is up to whether GUI is available or not.

You should be right. [diff-hl](https://github.com/dgutov/diff-hl) uses this function and it works for Emacs >25.1.

**Comment by AmaiKinono** [comment]
> I think I have some tricks to make the fringe borders look like having the same thickness as the horizontal borders.

image

It doesn't look very well. I'll stay with your approach.

A problem is the faces of the bottom 2 lines don't extend to the end. The reason is when replacing `\n` in the string, its face is dropped. But I've already fixed that.

**Comment by AmaiKinono** [comment]
Thanks!

**Pull request merged**
