### PR TITLE
global, enh: add function for global to update single file

### PR DESCRIPTION
**Pull request by norris-young**
global supports updating tags for a single file. we can add this function which might be used in after-save-hook.

### CODE REVIEW

**Comment by AmaiKinono** [comment]
Thanks, and sorry for the late response.

I've noticed the `tramp-file-name-localname`, `tramp-dissect-file-name` and `tramp-handle-expand-file-name` combination in your patch. I've used `file-local-name` for similar purpose in other parts of the code. Are they doing the same thing?

Also, seems `expand-filename` already does what `tramp-handle-expand-file-name` do:

``` elisp
(expand-file-name "/ssh:kino@localhost:~/.emacs.d/")
;; => "/ssh:kino@localhost:/home/kino/.emacs.d/"
```

So, could we replace it with something like `(file-local-name (expand-file-name filename))`, if they are doing the same thing? Then we can remove the dependency on TRAMP.

**Comment by norris-young** [comment]
> So, could we replace it with something like `(file-local-name (expand-file-name filename))`, if they are doing the same thing? Then we can remove the dependency on TRAMP.

It works and new patch has been pushed

**Comment by AmaiKinono** [comment]
Thanks!

**Comment by AmaiKinono** [comment]
> We can add this function which might be used in after-save-hook.

I'd like to ask how are you using this, as adding it to `after-save-hook` will prompt the user to create a global database for every file they save. Are there some special configuration on your side, or could we make it do nothing when no global database is found?

**Comment by norris-young** [comment]
> > We can add this function which might be used in after-save-hook.
> 
> I'd like to ask how are you using this, as adding it to `after-save-hook` will prompt the user to create a global database for every file they save. Are there some special configuration on your side, or could we make it do nothing when no global database is found?

FYI, I add some conditions.
```elisp
(lambda ()
  (when (and (eq major-mode 'c-ts-mode)
             (citre-global-dbpath))
    (citre-global-update-file)))
```

**Pull request merged**
