### PR TITLE
util, enh: show scope information in xref buffer

### PR DESCRIPTION
**Pull request by masatake**
Signed-off-by: Masatake YAMATO <yamato@redhat.com>

### CODE REVIEW

**Comment by AmaiKinono** [comment]
Thanks!

I really like the idea of using `@` for scope info. Maybe in the "interactively filtering" tool (that comes in the future), we can let the user type `@string` to filter tags whose scope contains `string`.

I have 2 more ideas:

- Give the separators (`/` and `@` in `kind/type@scope`) a different face.
- Truncate the long `__anon**` parts in scope and typeref info.

But that's for the future. For now, thanks for your work!

**Comment by masatake** [comment]
> Truncate the long __anon** parts in scope and typeref info.

Showing __anon** in an xref buffer can be useful. You can do "M-." on __anon** to jump to the definition.

**Comment by AmaiKinono** [comment]
> Showing __anon** in an xref buffer can be useful. You can do "M-." on __anon** to jump to the definition.

I see. It's still useful for `citre-jump` and `citre-peek` though. We can have a switch for it.

**Comment by AmaiKinono** [comment]
I just tried the situation you described. I can jump to an anonymous tag by `M-.`, but `citre-peek` will show me the definition of the line, not the symbol at point.

I'm thinking should we let `citre-peek` grab the symbol at point in annotations in xref buffer.

**Pull request merged**
